-- Generato da parse_excel.py
-- Source: Alpha Calulator.xlsx, Sheet "Skill Data"

DELETE FROM skill_levels;
DELETE FROM skills;

INSERT INTO skills (slug, name, max_level, type1, type2) VALUES
  ('adaptability', 'Adaptability', 2, 'armor', 'defensive'),
  ('aquatic_oilsilt_mobility', 'Aquatic/Oilsilt Mobility', 2, 'armor', 'defensive'),
  ('bind_resistence', 'Bind Resistence', 3, 'armor', 'defensive'),
  ('blast_resistence', 'Blast Resistence', 3, 'armor', 'defensive'),
  ('bleeding_resistence', 'Bleeding Resistence', 3, 'armor', 'defensive'),
  ('blight_reistence', 'Blight Reistence', 3, 'armor', 'defensive'),
  ('defense_boost', 'Defense Boost', 7, 'armor', 'defensive'),
  ('divine_blessing', 'Divine Blessing', 3, 'armor', 'defensive'),
  ('dragon_resistence', 'Dragon Resistence', 3, 'armor', 'defensive'),
  ('earplugs', 'Earplugs', 3, 'armor', 'defensive'),
  ('evade_extender', 'Evade Extender', 3, 'armor', 'defensive'),
  ('evade_window', 'Evade Window', 5, 'armor', 'defensive'),
  ('fire_resistence', 'Fire Resistence', 3, 'armor', 'defensive'),
  ('flinch_free', 'Flinch Free', 3, 'armor', 'defensive'),
  ('free_meal', 'Free Meal', 3, 'armor', 'defensive'),
  ('ice_resistence', 'Ice Resistence', 3, 'armor', 'defensive'),
  ('intimidator', 'Intimidator', 3, 'armor', 'defensive'),
  ('iron_skin', 'Iron Skin', 3, 'armor', 'defensive'),
  ('item_prolonger', 'Item Prolonger', 3, 'armor', 'defensive'),
  ('jump_master', 'Jump Master', 1, 'armor', 'defensive'),
  ('leap_of_faith', 'Leap Of Faith', 1, 'armor', 'defensive'),
  ('mashroomancer', 'Mashroomancer', 3, 'armor', 'defensive'),
  ('paralysis_resistence', 'Paralysis Resistence', 3, 'armor', 'defensive'),
  ('poison_resistence', 'Poison Resistence', 3, 'armor', 'defensive'),
  ('self_improvement', 'Self-Improvement', 1, 'armor', 'defensive'),
  ('shock_absorber', 'Shock Absorber', 1, 'armor', 'defensive'),
  ('sleep_resistence', 'Sleep Resistence', 3, 'armor', 'defensive'),
  ('speed_eating', 'Speed Eating', 3, 'armor', 'defensive'),
  ('strench_resistence', 'Strench Resistence', 3, 'armor', 'defensive'),
  ('stun_resistence', 'Stun Resistence', 3, 'armor', 'defensive'),
  ('thunder_resistence', 'Thunder Resistence', 3, 'armor', 'defensive'),
  ('tool_specialist', 'Tool Specialist', 5, 'armor', 'defensive'),
  ('tremor_reistence', 'Tremor Reistence', 3, 'armor', 'defensive'),
  ('water_resistence', 'Water Resistence', 3, 'armor', 'defensive'),
  ('wide_range', 'Wide Range', 5, 'armor', 'defensive'),
  ('windproof', 'WIndproof', 3, 'armor', 'defensive'),
  ('guardians_protection', 'Guardian''s Protection', 3, 'group', 'defensive'),
  ('guardians_pulse', 'Guardian''s Pulse', 3, 'group', 'defensive'),
  ('neopteron_camouflage', 'Neopteron Camouflage', 3, 'group', 'defensive'),
  ('gravios_protection', 'Gravios Protection', 4, 'series', 'defensive'),
  ('mizutsunes_prowess', 'Mizutsune''s Prowess', 4, 'series', 'defensive'),
  ('uth_dunas_cover', 'Uth Duna''s Cover', 4, 'series', 'defensive'),
  ('guard', 'Guard', 3, 'weapon', 'defensive'),
  ('guard_up', 'Guard Up', 3, 'weapon', 'defensive'),
  ('botanist', 'Botanist', 4, 'armor', 'farming'),
  ('entomologist', 'Entomologist', 1, 'armor', 'farming'),
  ('geologist', 'Geologist', 3, 'armor', 'farming'),
  ('outdoorsman', 'Outdoorsman', 1, 'armor', 'farming'),
  ('festival_spirit', 'Festival Spirit', 3, 'group', 'farming'),
  ('flexible_leathercraft', 'Flexible Leathercraft', 3, 'group', 'farming'),
  ('glorys_favor', 'Glory''s Favor', 3, 'group', 'farming'),
  ('imparted_wisdom', 'Imparted Wisdom', 3, 'group', 'farming'),
  ('neopteron_alert', 'Neopteron Alert', 3, 'group', 'farming'),
  ('blossomdance_prayer', 'Blossomdance Prayer', 4, 'series', 'farming'),
  ('flamefete_prayer', 'Flamefete Prayer', 4, 'series', 'farming'),
  ('adrenaline_rush', 'Adrenaline Rush', 5, 'armor', 'offensive'),
  ('agitator', 'Agitator', 5, 'armor', 'offensive'),
  ('ambush', 'Ambush', 3, 'armor', 'offensive'),
  ('antivirus', 'Antivirus', 3, 'armor', 'offensive'),
  ('bombardier', 'Bombardier', 3, 'armor', 'offensive'),
  ('burst', 'Burst', 5, 'armor', 'offensive'),
  ('coalescence', 'Coalescence', 3, 'armor', 'offensive'),
  ('convert_element', 'Convert Element', 3, 'armor', 'offensive'),
  ('counterstrike', 'Counterstrike', 3, 'armor', 'offensive'),
  ('elemental_absorbation', 'Elemental Absorbation', 3, 'armor', 'offensive'),
  ('flayer', 'Flayer', 5, 'armor', 'offensive'),
  ('foray', 'Foray', 5, 'armor', 'offensive'),
  ('heroics', 'Heroics', 5, 'armor', 'offensive'),
  ('latent_power', 'Latent Power', 5, 'armor', 'offensive'),
  ('maximun_might', 'Maximun Might', 3, 'armor', 'offensive'),
  ('palico_rally', 'Palico Rally', 5, 'armor', 'offensive'),
  ('partbreaker', 'Partbreaker', 3, 'armor', 'offensive'),
  ('peak_performance', 'Peak Performance', 5, 'armor', 'offensive'),
  ('resentment', 'Resentment', 5, 'armor', 'offensive'),
  ('weakness_exploit', 'Weakness Exploit', 5, 'armor', 'offensive'),
  ('buttery_leathercraft', 'Buttery Leathercraft', 3, 'group', 'offensive'),
  ('fortifyng_pelt', 'Fortifyng Pelt', 3, 'group', 'offensive'),
  ('lords_favor', 'Lord''s Favor', 3, 'group', 'offensive'),
  ('lords_fury', 'Lord''s Fury', 3, 'group', 'offensive'),
  ('lords_soul', 'Lord''s Soul', 3, 'group', 'offensive'),
  ('master_of_the_fist', 'Master of the Fist', 3, 'group', 'offensive'),
  ('blangongas_spirit', 'Blangonga''s Spirit', 4, 'series', 'offensive'),
  ('doshagumas_might', 'Doshaguma''s Might', 4, 'series', 'offensive'),
  ('ebony_odogarons_power', 'Ebony Odogaron''s Power', 4, 'series', 'offensive'),
  ('gore_magalas_tiranny', 'Gore Magala''s Tiranny', 4, 'series', 'offensive'),
  ('jin_dahaads_revolt', 'Jin Dahaad''s Revolt', 4, 'series', 'offensive'),
  ('leviathans_fury', 'Leviathan''s Fury', 4, 'series', 'offensive'),
  ('nu_udras_mutiny', 'Nu Udra''s Mutiny', 4, 'series', 'offensive'),
  ('rathaloss_flare', 'Rathalos''s Flare', 4, 'series', 'offensive'),
  ('rey_daus_voltage', 'Rey Dau''s Voltage', 4, 'series', 'offensive'),
  ('seregioss_tenacity', 'Seregios''s Tenacity', 4, 'series', 'offensive'),
  ('xu_wus_vigor', 'Xu Wu''s Vigor', 4, 'series', 'offensive'),
  ('airborne', 'Airborne', 1, 'weapon', 'offensive'),
  ('artillery', 'Artillery', 3, 'weapon', 'offensive'),
  ('attack_boost', 'Attack Boost', 5, 'weapon', 'offensive'),
  ('bladescale_honing', 'Bladescale Honing', 1, 'weapon', 'offensive'),
  ('bladescale_loading', 'Bladescale Loading', 1, 'weapon', 'offensive'),
  ('blast_attack', 'Blast Attack', 3, 'weapon', 'offensive'),
  ('bludgeoner', 'Bludgeoner', 3, 'weapon', 'offensive'),
  ('charge_master', 'Charge Master', 3, 'weapon', 'offensive'),
  ('convert_thunder_resistence', 'Convert Thunder Resistence', 1, 'weapon', 'offensive'),
  ('crackling_cornpopper', 'Crackling Cornpopper', 1, 'weapon', 'offensive'),
  ('critical_boost', 'Critical Boost', 5, 'weapon', 'offensive'),
  ('critical_draw', 'Critical Draw', 3, 'weapon', 'offensive'),
  ('critical_element', 'Critical Element', 3, 'weapon', 'offensive'),
  ('critical_eye', 'Critical Eye', 5, 'weapon', 'offensive'),
  ('critical_status', 'Critical Status', 3, 'weapon', 'offensive'),
  ('dragon_attack', 'Dragon Attack', 3, 'weapon', 'offensive'),
  ('fire_attack', 'Fire Attack', 3, 'weapon', 'offensive'),
  ('ice_attack', 'Ice Attack', 3, 'weapon', 'offensive'),
  ('minds_eye', 'Mind''s Eye', 3, 'weapon', 'offensive'),
  ('normal_shots', 'Normal Shots', 1, 'weapon', 'offensive'),
  ('offensive_guard', 'Offensive Guard', 3, 'weapon', 'offensive'),
  ('opening_shot', 'Opening Shot', 3, 'weapon', 'offensive'),
  ('paralysis_attack', 'Paralysis Attack', 3, 'weapon', 'offensive'),
  ('piercing_shots', 'Piercing Shots', 1, 'weapon', 'offensive'),
  ('poison_attack', 'Poison Attack', 3, 'weapon', 'offensive'),
  ('punishing_draw', 'Punishing Draw', 3, 'weapon', 'offensive'),
  ('rapid_fire_up', 'Rapid Fire Up', 1, 'weapon', 'offensive'),
  ('sleep_attack', 'Sleep Attack', 3, 'weapon', 'offensive'),
  ('slicked_blade', 'Slicked Blade', 3, 'weapon', 'offensive'),
  ('special_ammo_boost', 'Special Ammo Boost', 2, 'weapon', 'offensive'),
  ('spred_power_shots', 'Spred/Power Shots', 1, 'weapon', 'offensive'),
  ('tedrad_shot', 'Tedrad Shot', 3, 'weapon', 'offensive'),
  ('thunder_attack', 'Thunder Attack', 3, 'weapon', 'offensive'),
  ('water_attack', 'Water Attack', 3, 'weapon', 'offensive'),
  ('whiteflame_torrent', 'Whiteflame Torrent', 1, 'weapon', 'offensive'),
  ('recovery_speed', 'Recovery Speed', 3, 'armor', 'regen'),
  ('recovery_up', 'Recovery Up', 3, 'armor', 'regen'),
  ('survival_expert', 'Survival Expert', 3, 'armor', 'regen'),
  ('arkvelds_hunger', 'Arkveld''s Hunger', 4, 'series', 'regen'),
  ('guardian_arkvelds_vitality', 'Guardian Arkveld''s Vitality', 4, 'series', 'regen'),
  ('zoh_shias_pulse', 'Zoh Shia''s Pulse', 4, 'series', 'regen'),
  ('handicraft', 'Handicraft', 5, 'Weapon', 'Sharpness Managment'),
  ('masters_touch', 'Master''s Touch', 1, 'Weapon', 'Sharpness Managment'),
  ('protective_polish', 'Protective Polish', 3, 'Weapon', 'Sharpness Managment'),
  ('razor_sharp', 'Razor Sharp', 3, 'Weapon', 'Sharpness Managment'),
  ('speed_sharpening', 'Speed Sharpening', 2, 'Weapon', 'Sharpness Managment'),
  ('cliffhanger', 'Cliffhanger', 1, 'Armor', 'Stamina management'),
  ('constitution', 'Constitution', 5, 'Armor', 'Stamina management'),
  ('hunger_resistence', 'Hunger Resistence', 3, 'Armor', 'Stamina management'),
  ('marathon_runner', 'Marathon Runner', 3, 'Armor', 'Stamina management'),
  ('stamina_surge', 'Stamina Surge', 3, 'Armor', 'Stamina management'),
  ('scale_layering', 'Scale Layering', 3, 'Group', 'Stamina management'),
  ('fulgur_anjanaths_will', 'Fulgur Anjanath''s WIll', 4, 'Series', 'Stamina management'),
  ('blindsider', 'Blindsider', 1, 'armor', 'technical'),
  ('quick_sheathe', 'Quick Sheathe', 3, 'armor', 'technical'),
  ('alluring_pelt', 'Alluring Pelt', 3, 'group', 'technical'),
  ('scaling_prowess', 'Scaling Prowess', 3, 'group', 'technical'),
  ('ballistics', 'Ballistics', 3, 'weapon', 'technical'),
  ('blast_functionality', 'Blast Functionality', 1, 'weapon', 'technical'),
  ('charge_up', 'Charge Up', 1, 'weapon', 'technical'),
  ('evading_reload', 'Evading Reload', 1, 'weapon', 'technical'),
  ('exhaust_funcionality', 'Exhaust Funcionality', 1, 'weapon', 'technical'),
  ('focus', 'Focus', 3, 'weapon', 'technical'),
  ('horn_maestro', 'Horn Maestro', 2, 'weapon', 'technical'),
  ('load_shell', 'Load Shell', 2, 'weapon', 'technical'),
  ('para_funcionality', 'Para Funcionality', 1, 'weapon', 'technical'),
  ('poison_duration_up', 'Poison Duration Up', 1, 'weapon', 'technical'),
  ('poison_functionality', 'Poison Functionality', 1, 'weapon', 'technical'),
  ('power_prolonger', 'Power Prolonger', 3, 'weapon', 'technical'),
  ('rapid_morph', 'Rapid Morph', 3, 'weapon', 'technical'),
  ('sleep_functionality', 'Sleep Functionality', 1, 'weapon', 'technical'),
  ('slugger', 'Slugger', 3, 'weapon', 'technical'),
  ('stamina_thief', 'Stamina Thief', 3, 'weapon', 'technical'),
  ('darkside', 'Darkside', 1, 'weapon', 'offensive'),
  ('dark_arts', 'Dark Arts', 2, 'series', 'offensive'),
  ('the_blackest_night', 'the Blackest Night', 4, 'armor', 'utility');
