-- Generato da parse_excel.py
-- Source: Alpha Calulator.xlsx, Sheet "Skill Data"

INSERT INTO skill_levels (skill_id, level, bonus1_value, bonus1_type, bonus2_value, bonus2_type, bonus3_value, bonus3_type, duration_s, cooldown_s) VALUES
  ('adaptability', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('adaptability', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('aquatic_oilsilt_mobility', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('aquatic_oilsilt_mobility', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('bind_resistence', 1, NULL, 'Blight reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bind_resistence', 2, NULL, 'Blight reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bind_resistence', 3, NULL, 'Blight reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('blast_resistence', 1, NULL, 'Blastblight''s Delay', 0.66, 'Blast damage reduction', NULL, NULL, NULL, NULL),
  ('blast_resistence', 2, NULL, 'Blastblight''s Delay', 0.5, 'Blast damage reduction', NULL, NULL, NULL, NULL),
  ('blast_resistence', 3, NULL, 'Blastblight''s Delay', 0.0, 'Blast damage reduction', NULL, NULL, NULL, NULL),
  ('bleeding_resistence', 1, NULL, 'Damage Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bleeding_resistence', 2, NULL, 'Damage Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bleeding_resistence', 3, NULL, 'Damage Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('blight_reistence', 1, NULL, 'Duration''s Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('blight_reistence', 2, NULL, 'Duration''s Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('blight_reistence', 3, NULL, 'Duration''s Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('defense_boost', 1, 1.0, 'def_multiplier', 5.0, 'def_additive', 0.0, 'elem_res_additive', NULL, NULL),
  ('defense_boost', 2, 1.0, 'def_multiplier', 10.0, 'def_additive', 0.0, 'elem_res_additive', NULL, NULL),
  ('defense_boost', 3, 1.05, 'def_multiplier', 10.0, 'def_additive', 0.0, 'elem_res_additive', NULL, NULL),
  ('defense_boost', 4, 1.05, 'def_multiplier', 20.0, 'def_additive', 3.0, 'elem_res_additive', NULL, NULL),
  ('defense_boost', 5, 1.05, 'def_multiplier', 20.0, 'def_additive', 3.0, 'elem_res_additive', NULL, NULL),
  ('defense_boost', 6, 1.05, 'def_multiplier', 35.0, 'def_additive', 5.0, 'elem_res_additive', NULL, NULL),
  ('defense_boost', 7, 1.1, 'def_multiplier', 35.0, 'def_additive', 5.0, 'elem_res_additive', NULL, NULL),
  ('divine_blessing', 1, NULL, 'Damage Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('divine_blessing', 2, NULL, 'Damage Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('divine_blessing', 3, NULL, 'Damage Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('dragon_resistence', 1, 6.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('dragon_resistence', 2, 12.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('dragon_resistence', 3, 20.0, 'elem_res_additive', 10.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('earplugs', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('earplugs', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('earplugs', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_extender', 1, 0.125, 'Evasion distance', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_extender', 2, 0.1875, 'Evasion distance', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_extender', 3, 0.25, 'Evasion distance', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_window', 1, 17.0, 'i-frames', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_window', 2, 19.0, 'i-frames', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_window', 3, 21.0, 'i-frames', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_window', 4, 23.0, 'i-frames', NULL, NULL, NULL, NULL, NULL, NULL),
  ('evade_window', 5, 28.0, 'i-frames', NULL, NULL, NULL, NULL, NULL, NULL),
  ('fire_resistence', 1, 6.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('fire_resistence', 2, 12.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('fire_resistence', 3, 20.0, 'elem_res_additive', 10.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('flinch_free', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('flinch_free', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('flinch_free', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('free_meal', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('free_meal', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('free_meal', 3, 0.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ice_resistence', 1, 6.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('ice_resistence', 2, 12.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('ice_resistence', 3, 20.0, 'elem_res_additive', 10.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('intimidator', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('intimidator', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('intimidator', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('iron_skin', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('iron_skin', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('iron_skin', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('item_prolonger', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('item_prolonger', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('item_prolonger', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('jump_master', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('leap_of_faith', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mashroomancer', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mashroomancer', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mashroomancer', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('paralysis_resistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('paralysis_resistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('paralysis_resistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('poison_resistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('poison_resistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('poison_resistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('self_improvement', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('shock_absorber', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sleep_resistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sleep_resistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sleep_resistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('speed_eating', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('speed_eating', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('speed_eating', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('strench_resistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('strench_resistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('strench_resistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stun_resistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stun_resistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stun_resistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('thunder_resistence', 1, 6.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('thunder_resistence', 2, 12.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('thunder_resistence', 3, 20.0, 'elem_res_additive', 10.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('tool_specialist', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tool_specialist', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tool_specialist', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tool_specialist', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tool_specialist', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tremor_reistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tremor_reistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tremor_reistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('water_resistence', 1, 6.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('water_resistence', 2, 12.0, 'elem_res_additive', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('water_resistence', 3, 20.0, 'elem_res_additive', 10.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('wide_range', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('wide_range', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('wide_range', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('wide_range', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('wide_range', 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('windproof', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('windproof', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('windproof', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guardians_protection', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guardians_pulse', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('neopteron_camouflage', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('gravios_protection', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('gravios_protection', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mizutsunes_prowess', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mizutsunes_prowess', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('uth_dunas_cover', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('uth_dunas_cover', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guard', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guard', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guard', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guard_up', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guard_up', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guard_up', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('botanist', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('botanist', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('botanist', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('botanist', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('entomologist', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('geologist', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('geologist', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('geologist', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('outdoorsman', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('festival_spirit', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('flexible_leathercraft', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('glorys_favor', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('imparted_wisdom', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('neopteron_alert', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('blossomdance_prayer', 2, 1.0, 'atk_multiplier', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('blossomdance_prayer', 4, 0.04791666666666667, 'atk_multiplier', 50.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('flamefete_prayer', 2, 1.0, 'atk_multiplier', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('flamefete_prayer', 4, 0.04791666666666667, 'atk_multiplier', 50.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('adrenaline_rush', 1, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('adrenaline_rush', 2, 15.0, 'atk_additive', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('adrenaline_rush', 3, 20.0, 'atk_additive', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('adrenaline_rush', 4, 25.0, 'atk_additive', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('adrenaline_rush', 5, 30.0, 'atk_additive', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('agitator', 1, 4.0, 'atk_additive', 0.03, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('agitator', 2, 8.0, 'atk_additive', 0.05, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('agitator', 3, 12.0, 'atk_additive', 0.07, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('agitator', 4, 16.0, 'atk_additive', 0.1, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('agitator', 5, 20.0, 'atk_additive', 0.15, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('ambush', 1, 0.05, 'atk_multiplier', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('ambush', 2, 0.1, 'atk_multiplier', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('ambush', 3, 0.15, 'atk_multiplier', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('antivirus', 1, 0.03, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('antivirus', 2, 0.06, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('antivirus', 3, 0.1, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bombardier', 1, 1.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bombardier', 2, 1.2, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bombardier', 3, 1.3, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('burst', 1, 8.0, 'atk_additive', 60.0, 'elem_additive', NULL, NULL, 4.0, NULL),
  ('burst', 2, 10.0, 'atk_additive', 80.0, 'elem_additive', NULL, NULL, 4.0, NULL),
  ('burst', 3, 12.0, 'atk_additive', 100.0, 'elem_additive', NULL, NULL, 4.0, NULL),
  ('burst', 4, 15.0, 'atk_additive', 120.0, 'elem_additive', NULL, NULL, 4.0, NULL),
  ('burst', 5, 18.0, 'atk_additive', 140.0, 'elem_additive', NULL, NULL, 4.0, NULL),
  ('coalescence', 1, 0.1, 'elem_multiplier', 0.05, 'Moltiplier (status)', NULL, NULL, 30.0, NULL),
  ('coalescence', 2, 0.2, 'elem_multiplier', 0.1, 'Moltiplier (status)', NULL, NULL, 30.0, NULL),
  ('coalescence', 3, 0.3, 'elem_multiplier', 0.15, 'Moltiplier (status)', NULL, NULL, 30.0, NULL),
  ('convert_element', 1, NULL, 'Dragon blast', 60.0, 'elem_additive', NULL, NULL, 120.0, 90.0),
  ('convert_element', 2, NULL, 'Dragon blast', 120.0, 'elem_additive', NULL, NULL, 120.0, 90.0),
  ('convert_element', 3, NULL, 'Dragon blast', 180.0, 'elem_additive', NULL, NULL, 120.0, 90.0),
  ('counterstrike', 1, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('counterstrike', 2, 15.0, 'atk_additive', NULL, NULL, NULL, NULL, 35.0, NULL),
  ('counterstrike', 3, 25.0, 'atk_additive', NULL, NULL, NULL, NULL, 45.0, NULL),
  ('elemental_absorbation', 1, 40.0, 'elem_additive', 4.0, 'elem_res_additive', NULL, NULL, 120.0, 90.0),
  ('elemental_absorbation', 2, 50.0, 'elem_additive', 5.0, 'elem_res_additive', NULL, NULL, 120.0, 90.0),
  ('elemental_absorbation', 3, 60.0, 'elem_additive', 6.0, 'elem_res_additive', NULL, NULL, 120.0, 90.0),
  ('flayer', 1, 0.05, 'Moltiplier (Wound)', 140.0, 'Flayer blast', NULL, NULL, NULL, NULL),
  ('flayer', 2, 0.1, 'Moltiplier (Wound)', 160.0, 'Flayer blast', NULL, NULL, NULL, NULL),
  ('flayer', 3, 0.15, 'Moltiplier (Wound)', 190.0, 'Flayer blast', NULL, NULL, NULL, NULL),
  ('flayer', 4, 0.2, 'Moltiplier (Wound)', 230.0, 'Flayer blast', NULL, NULL, NULL, NULL),
  ('flayer', 5, 0.3, 'Moltiplier (Wound)', 280.0, 'Flayer blast', NULL, NULL, NULL, NULL),
  ('foray', 1, 6.0, 'atk_additive', 0.0, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('foray', 2, 8.0, 'atk_additive', 0.05, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('foray', 3, 10.0, 'atk_additive', 0.1, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('foray', 4, 12.0, 'atk_additive', 0.15, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('foray', 5, 15.0, 'atk_additive', 0.2, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('heroics', 1, 0.0, 'atk_multiplier', 50.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('heroics', 2, 0.05, 'atk_multiplier', 50.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('heroics', 3, 0.05, 'atk_multiplier', 100.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('heroics', 4, 0.1, 'atk_multiplier', 100.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('heroics', 5, 0.3, 'atk_multiplier', 0.0, 'def_additive', NULL, NULL, NULL, NULL),
  ('latent_power', 1, 0.1, 'affinity_additive', 0.7, 'Stamina depletion', NULL, NULL, 90.0, 120.0),
  ('latent_power', 2, 0.2, 'affinity_additive', 0.6, 'Stamina depletion', NULL, NULL, 90.0, 120.0),
  ('latent_power', 3, 0.3, 'affinity_additive', 0.5, 'Stamina depletion', NULL, NULL, 90.0, 120.0),
  ('latent_power', 4, 0.4, 'affinity_additive', 0.5, 'Stamina depletion', NULL, NULL, 90.0, 120.0),
  ('latent_power', 5, 0.5, 'affinity_additive', 0.5, 'Stamina depletion', NULL, NULL, 90.0, 120.0),
  ('maximun_might', 1, 0.1, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('maximun_might', 2, 0.2, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('maximun_might', 3, 0.3, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('palico_rally', 1, 1.05, 'Moltiplier (palico atk)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('palico_rally', 2, 1.1, 'Moltiplier (palico atk)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('palico_rally', 3, 1.15, 'Moltiplier (palico atk)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('palico_rally', 4, 1.2, 'Moltiplier (palico atk)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('palico_rally', 5, 1.25, 'Moltiplier (palico atk)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('partbreaker', 1, 1.1, 'Moltiplier(partbreak)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('partbreaker', 2, 1.2, 'Moltiplier(partbreak)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('partbreaker', 3, 1.3, 'Moltiplier(partbreak)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('peak_performance', 1, 3.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('peak_performance', 2, 6.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('peak_performance', 3, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('peak_performance', 4, 15.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('peak_performance', 5, 20.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('resentment', 1, 5.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('resentment', 2, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('resentment', 3, 15.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('resentment', 4, 20.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('resentment', 5, 25.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('weakness_exploit', 1, 0.05, 'affinity_additive', 0.03, NULL, NULL, NULL, NULL, NULL),
  ('weakness_exploit', 2, 0.1, 'affinity_additive', 0.05, NULL, NULL, NULL, NULL, NULL),
  ('weakness_exploit', 3, 0.15, 'affinity_additive', 0.1, NULL, NULL, NULL, NULL, NULL),
  ('weakness_exploit', 4, 0.2, 'affinity_additive', 0.15, NULL, NULL, NULL, NULL, NULL),
  ('weakness_exploit', 5, 0.3, 'affinity_additive', 0.2, NULL, NULL, NULL, NULL, NULL),
  ('buttery_leathercraft', 3, 0.3, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('fortifyng_pelt', 3, 1.1, 'atk_multiplier', 1.15, 'def_multiplier', NULL, NULL, NULL, NULL),
  ('lords_favor', 3, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('lords_fury', 3, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('lords_soul', 3, 1.05, 'atk_multiplier', 0.95, 'def_multiplier', NULL, NULL, NULL, NULL),
  ('master_of_the_fist', 3, 1.5, 'Moltiplier (Fist Dmg)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('blangongas_spirit', 2, 3.0, 'atk_additive', NULL, NULL, NULL, NULL, 90.0, NULL),
  ('blangongas_spirit', 4, 6.0, 'atk_additive', NULL, NULL, NULL, NULL, 90.0, NULL),
  ('doshagumas_might', 2, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, 180.0, NULL),
  ('doshagumas_might', 4, 25.0, 'atk_additive', NULL, NULL, NULL, NULL, 180.0, NULL),
  ('ebony_odogarons_power', 2, 8.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('ebony_odogarons_power', 4, 18.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('gore_magalas_tiranny', 2, 0.15, 'affinity_additive', 0.0, NULL, 0.0, NULL, 60.0, NULL),
  ('gore_magalas_tiranny', 4, 0.15, 'affinity_additive', 10.0, 'atk_additive', 15.0, 'atk_additive', 60.0, NULL),
  ('jin_dahaads_revolt', 2, 25.0, 'atk_additive', NULL, NULL, NULL, NULL, 60.0, NULL),
  ('jin_dahaads_revolt', 4, 50.0, 'atk_additive', NULL, NULL, NULL, NULL, 60.0, NULL),
  ('leviathans_fury', 2, 0.15, 'affinity_additive', 30.0, 'Fixed raw damage', 70.0, 'Elemental damage', 20.0, 30.0),
  ('leviathans_fury', 4, 0.15, 'affinity_additive', 60.0, 'Fixed raw damage', 200.0, 'Elemental damage', 30.0, 30.0),
  ('nu_udras_mutiny', 2, 25.0, 'Proc Damage (raw)', NULL, NULL, NULL, NULL, NULL, 4.0),
  ('nu_udras_mutiny', 4, 60.0, 'Proc Damage (raw)', NULL, NULL, NULL, NULL, NULL, 4.0),
  ('rathaloss_flare', 2, 40.0, 'Proc damage (elem)', NULL, NULL, NULL, NULL, NULL, 6.0),
  ('rathaloss_flare', 4, 100.0, 'Proc damage (elem)', NULL, NULL, NULL, NULL, NULL, 6.0),
  ('rey_daus_voltage', 2, 150.0, 'Latent power''s duration', NULL, NULL, NULL, NULL, NULL, NULL),
  ('rey_daus_voltage', 4, 210.0, 'Latent power''s duration', NULL, NULL, NULL, NULL, NULL, NULL),
  ('seregioss_tenacity', 2, 1.0, 'atk_multiplier', 45.0, 'adrenaline rush''s duration', NULL, NULL, NULL, NULL),
  ('seregioss_tenacity', 4, 1.05, 'atk_multiplier', 60.0, 'adrenaline rush''s duration', NULL, NULL, NULL, NULL),
  ('xu_wus_vigor', 2, 15.0, 'atk_additive', NULL, NULL, NULL, NULL, 120.0, NULL),
  ('xu_wus_vigor', 4, 25.0, 'atk_additive', NULL, NULL, NULL, NULL, 120.0, NULL),
  ('airborne', 1, 1.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('artillery', 1, 1.05, 'Moltiplier (Wyvern''s fire dmg)', 3.0, 'Additive (Fire dmg Shell)', 1.1, 'Moltiplier (explosive dmg)', NULL, NULL),
  ('artillery', 2, 1.1, 'Moltiplier (Wyvern''s fire dmg)', 6.0, 'Additive (Fire dmg Shell)', 1.2, 'Moltiplier (explosive dmg)', NULL, NULL),
  ('artillery', 3, 1.15, 'Moltiplier (Wyvern''s fire dmg)', 9.0, 'Additive (Fire dmg Shell)', 1.3, 'Moltiplier (explosive dmg)', NULL, NULL),
  ('attack_boost', 1, 1.0, 'atk_multiplier', 3.0, 'atk_additive', NULL, NULL, NULL, NULL),
  ('attack_boost', 2, 1.0, 'atk_multiplier', 5.0, 'atk_additive', NULL, NULL, NULL, NULL),
  ('attack_boost', 3, 1.0, 'atk_multiplier', 7.0, 'atk_additive', NULL, NULL, NULL, NULL),
  ('attack_boost', 4, 1.02, 'atk_multiplier', 8.0, 'atk_additive', NULL, NULL, NULL, NULL),
  ('attack_boost', 5, 1.04, 'atk_multiplier', 9.0, 'atk_additive', NULL, NULL, NULL, NULL),
  ('bladescale_honing', 1, 1.339, 'sharpness_modifier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bladescale_loading', 1, 1.25, 'elem_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('blast_attack', 1, 1.05, 'Moltiplier (buildup)', 10.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('blast_attack', 2, 1.1, 'Moltiplier (buildup)', 20.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('blast_attack', 3, 1.2, 'Moltiplier (buildup)', 50.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('bludgeoner', 1, 1.05, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bludgeoner', 2, 1.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('bludgeoner', 3, 1.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('charge_master', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('charge_master', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('charge_master', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('convert_thunder_resistence', 1, 4.0, 'additive (thunder)', NULL, NULL, NULL, NULL, NULL, NULL),
  ('crackling_cornpopper', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_boost', 1, 0.28, 'crit_bonus', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_boost', 2, 0.31, 'crit_bonus', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_boost', 3, 0.34, 'crit_bonus', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_boost', 4, 0.37, 'crit_bonus', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_boost', 5, 0.4, 'crit_bonus', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_draw', 1, 0.5, 'affinity_additive', NULL, NULL, NULL, NULL, 2.0, NULL),
  ('critical_draw', 2, 0.75, 'affinity_additive', NULL, NULL, NULL, NULL, 2.0, NULL),
  ('critical_draw', 3, 1.0, 'affinity_additive', NULL, NULL, NULL, NULL, 2.0, NULL),
  ('critical_element', 1, 0.07, 'crit_elem_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_element', 2, 0.14, 'crit_elem_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_element', 3, 0.21, 'crit_elem_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_eye', 1, 0.04, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_eye', 2, 0.08, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_eye', 3, 0.12, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_eye', 4, 0.16, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_eye', 5, 0.2, 'affinity_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_status', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_status', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('critical_status', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('dragon_attack', 1, 1.0, 'elem_multiplier', 40.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('dragon_attack', 2, 1.1, 'elem_multiplier', 50.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('dragon_attack', 3, 1.2, 'elem_multiplier', 60.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('fire_attack', 1, 1.0, 'elem_multiplier', 40.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('fire_attack', 2, 1.1, 'elem_multiplier', 50.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('fire_attack', 3, 1.2, 'elem_multiplier', 60.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('ice_attack', 1, 1.0, 'elem_multiplier', 40.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('ice_attack', 2, 1.1, 'elem_multiplier', 50.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('ice_attack', 3, 1.2, 'elem_multiplier', 60.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('minds_eye', 1, 0.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('minds_eye', 2, 0.15, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('minds_eye', 3, 0.3, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('normal_shots', 1, 1.05, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('offensive_guard', 1, 0.05, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('offensive_guard', 2, 0.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('offensive_guard', 3, 0.15, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('opening_shot', 1, 5.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('opening_shot', 2, 10.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('opening_shot', 3, 15.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('paralysis_attack', 1, 1.05, 'Moltiplier (buildup)', 10.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('paralysis_attack', 2, 1.1, 'Moltiplier (buildup)', 20.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('paralysis_attack', 3, 1.2, 'Moltiplier (buildup)', 50.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('piercing_shots', 1, 1.05, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('poison_attack', 1, 1.05, 'Moltiplier (buildup)', 10.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('poison_attack', 2, 1.1, 'Moltiplier (buildup)', 20.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('poison_attack', 3, 1.2, 'Moltiplier (buildup)', 50.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('punishing_draw', 1, 3.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('punishing_draw', 2, 5.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('punishing_draw', 3, 7.0, 'atk_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('rapid_fire_up', 1, 1.05, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('sleep_attack', 1, 1.05, 'Moltiplier (buildup)', 10.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('sleep_attack', 2, 1.1, 'Moltiplier (buildup)', 20.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('sleep_attack', 3, 1.2, 'Moltiplier (buildup)', 50.0, 'Additive (Status)', NULL, NULL, NULL, NULL),
  ('slicked_blade', 1, 0.07, 'affinity_additive', 0.03, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('slicked_blade', 2, 0.14, 'affinity_additive', 0.06, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('slicked_blade', 3, 0.21, 'affinity_additive', 0.09, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('special_ammo_boost', 1, 1.1, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('special_ammo_boost', 2, 1.2, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('spred_power_shots', 1, 1.05, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('tedrad_shot', 1, 3.0, 'atk_additive', 0.08, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('tedrad_shot', 2, 6.0, 'atk_additive', 0.1, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('tedrad_shot', 3, 10.0, 'atk_additive', 0.12, 'affinity_additive', NULL, NULL, NULL, NULL),
  ('thunder_attack', 1, 1.0, 'elem_multiplier', 40.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('thunder_attack', 2, 1.1, 'elem_multiplier', 50.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('thunder_attack', 3, 1.2, 'elem_multiplier', 60.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('water_attack', 1, 1.0, 'elem_multiplier', 40.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('water_attack', 2, 1.1, 'elem_multiplier', 50.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('water_attack', 3, 1.2, 'elem_multiplier', 60.0, 'elem_additive', NULL, NULL, NULL, NULL),
  ('whiteflame_torrent', 1, 50.0, 'Proc (fixed damage)', NULL, NULL, NULL, NULL, 6.0, NULL),
  ('recovery_speed', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('recovery_speed', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('recovery_speed', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('recovery_up', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('recovery_up', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('recovery_up', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('survival_expert', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('survival_expert', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('survival_expert', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('arkvelds_hunger', 2, 14.0, 'Hp regen', NULL, NULL, NULL, NULL, NULL, NULL),
  ('arkvelds_hunger', 4, 20.0, 'Hp regen', NULL, NULL, NULL, NULL, NULL, NULL),
  ('guardian_arkvelds_vitality', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('guardian_arkvelds_vitality', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('zoh_shias_pulse', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('zoh_shias_pulse', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('handicraft', 1, 10.0, 'sharpness_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('handicraft', 2, 20.0, 'sharpness_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('handicraft', 3, 30.0, 'sharpness_additive', NULL, NULL, NULL, NULL, NULL, NULL),
  ('handicraft', 4, 40.0, 'Additional sharpness hits', NULL, NULL, NULL, NULL, NULL, NULL),
  ('handicraft', 5, 50.0, 'Additional sharpness hits', NULL, NULL, NULL, NULL, NULL, NULL),
  ('masters_touch', 1, 0.8, 'sharpness_consumption_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('protective_polish', 1, 1e-05, 'Seconds of infinite sharpenss', NULL, NULL, NULL, NULL, 30.0, NULL),
  ('protective_polish', 2, 1e-05, 'Seconds of infinite sharpenss', NULL, NULL, NULL, NULL, 60.0, NULL),
  ('protective_polish', 3, 1e-05, 'Seconds of infinite sharpenss', NULL, NULL, NULL, NULL, 90.0, NULL),
  ('razor_sharp', 1, 0.1, 'sharpness_consumption_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('razor_sharp', 2, 0.25, 'sharpness_consumption_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('razor_sharp', 3, 0.5, 'sharpness_consumption_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('speed_sharpening', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('speed_sharpening', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('cliffhanger', 1, 0.5, 'Stamina Reduction', NULL, NULL, NULL, NULL, NULL, NULL),
  ('constitution', 1, 0.9, 'Stamina Depletion', NULL, NULL, NULL, NULL, NULL, NULL),
  ('constitution', 2, 0.8, 'Stamina Depletion', NULL, NULL, NULL, NULL, NULL, NULL),
  ('constitution', 3, 0.7, 'Stamina Depletion', NULL, NULL, NULL, NULL, NULL, NULL),
  ('constitution', 4, 0.6, 'Stamina Depletion', NULL, NULL, NULL, NULL, NULL, NULL),
  ('constitution', 5, 0.5, 'Stamina Depletion', NULL, NULL, NULL, NULL, NULL, NULL),
  ('hunger_resistence', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('hunger_resistence', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('hunger_resistence', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('marathon_runner', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('marathon_runner', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('marathon_runner', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stamina_surge', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stamina_surge', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stamina_surge', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('scale_layering', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('fulgur_anjanaths_will', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('fulgur_anjanaths_will', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('blindsider', 1, 200.0, 'Flashes'' effect', NULL, NULL, NULL, NULL, NULL, NULL),
  ('quick_sheathe', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('quick_sheathe', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('quick_sheathe', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('alluring_pelt', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('scaling_prowess', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ballistics', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ballistics', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ballistics', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('blast_functionality', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('charge_up', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('evading_reload', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('exhaust_funcionality', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('focus', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('focus', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('focus', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('horn_maestro', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('horn_maestro', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('load_shell', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('load_shell', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('para_funcionality', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('poison_duration_up', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('poison_functionality', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('power_prolonger', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('power_prolonger', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('power_prolonger', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('rapid_morph', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('rapid_morph', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('rapid_morph', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sleep_functionality', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('slugger', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('slugger', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('slugger', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stamina_thief', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stamina_thief', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('stamina_thief', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('darkside', 1, 1.1, 'atk_multiplier', NULL, NULL, NULL, NULL, 30.0, 15.0),
  ('dark_arts', 2, 1.2, 'atk_multiplier', NULL, NULL, NULL, NULL, NULL, NULL),
  ('the_blackest_night', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
